apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: api-data
              mountPath: /opt/app/uploads
              subPath: backend
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_PASSWORD
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_HOSTNAME
      volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: api-pvc

# DATABASE_URL
#postgresql://demo:demo@rabbitmq-clusterip:5432/demo

