apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: conv
  template:
    metadata:
      labels:
        components: conv
    spec:
      containers:
        - name: conv
          image: antonlarichev/conv-api
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_PASSWORD
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_HOSTNAME
            - name: AMQP_QUEUE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_QUEUE

