apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: frontend
  template:
    metadata:
      name: conv-app
      labels:
        components: frontend
    spec:
      containers:
        - name: conv-app
          image: antonlarichev/conv-app
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: VITE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: VITE_DOMAIN
          volumeMounts:
            - name: test
              mountPath: /etc/test
              readOnly: true
      volumes:
        - name: test
          configMap:
            name: demo-config


