apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.conv.name }}-deployment
spec:
  replicas: {{ .Values.conv.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.conv.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.conv.components }}
    spec:
      containers:
        - name: {{ .Values.conv.name }}
          image: {{ .Values.conv.image }}
          ports:
            - containerPort: {{ .Values.conv.port }}
          resources:
            limits: {{ .Values.conv.limits | toYml | nindent 14 }}
          env:
            {{- range .Values.conv.envs }}
            {{- $data := dict "name" $.Values.rabbitmq.name "end" . }}
            {{- include "env.tmpl"  $data | indent 12}}
            {{- end }}
            # - name: AMQP_EXCHANGE
            #   valueFrom:
            #     secretKeyRef:
            #       name: rabbitmq-secret
            #       key: AMQP_EXCHANGE
            # - name: AMQP_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: rabbitmq-secret
            #       key: AMQP_USER
            # - name: AMQP_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: rabbitmq-secret
            #       key: AMQP_PASSWORD
            # - name: AMQP_HOSTNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: rabbitmq-secret
            #       key: AMQP_HOSTNAME
            # - name: AMQP_QUEUE
            #   valueFrom:
            #     secretKeyRef:
            #       name: rabbitmq-secret
            #       key: AMQP_QUEUE

